### PR TITLE
store sparsity structure inside CUTEstModel

### PR DESCRIPTION
**Pull request by dpo**
jac_coord! and hess_coord! should not assume that the rows and cols
index vectors are well defined and should not try to access them

### CODE REVIEW

**Comment by abelsiqueira** [comment]
Thank you. I think we can release now, right?

**Comment by dpo** [comment]
@PEPERSO Could you test this with NCL?

**Comment by dpo** [comment]
@abelsiqueira It should be good, but let's test it to make sure.

**Comment by PEPERSO** [comment]
@dpo All my test with ```NCL``` passed, and I made sure to use ```hess_structure!``` and ```jac_structure!``` in my model, so it should be alright.

**Comment by dpo** [comment]
Excellent, thank you!

**Pull request merged**
