### PR TITLE
Linuxbrew

### PR DESCRIPTION
**Pull request by dpo**
cf #134

### CODE REVIEW

**Comment by dpo** [comment]
@abelsiqueira This build succeeded but I had to pre-install gfortran on the Linux VM. I'll see if it's possible to use Linuxbrew's own gfortran.

**Comment by abelsiqueira** [comment]
Maybe `Linuxbrew.add("patchelf")` could be a part of the `build.jl`.

**Comment by abelsiqueira** [comment]
What do we do here? I don't use Linuxbrew for anything - it's not so useful on linux - but it uses the same bottle as homebrew, which should be easier to maintain. The hardest thing was finding `libgfortran.so`, because it's different on different Ubuntu versions, and on Archlinux, but I think the latest `linux-cutest` and the updates on the installation have mostly fixed that.

**Comment by dpo** [comment]
The one advantage I see to Linuxbrew is that it's useful if you don't have admin privileges (and you can't `apt-get install` something). But it's not perfect and sometimes it's a pain. Why do you say it's not so useful?

**Comment by abelsiqueira** [comment]
Most distributions come with a package manager (`apt-get`, or in my case `pacman`), which generally has most of what the users need. Possibly the niche packages, but I haven't used it. But you're right about the privileges.

**Pull request closed without merging**
