### PR TITLE
rely on generic MPB interface

### PR DESCRIPTION
**Pull request by dpo**
See https://github.com/JuliaSmoothOptimizers/NLPModels.jl/pull/45.

### CODE REVIEW

**Comment by dpo** [comment]
Good to go.

**Comment by abelsiqueira** [comment]
It has conflicts, can you rebase it?

**Comment by dpo** [comment]
Done. Strange, a minute ago, the lights were all green.

**Comment by abelsiqueira** [comment]
Sometimes github doesn't update without a hard refresh.

**Comment by abelsiqueira** [comment]
Thanks

**Pull request merged**
