### PR TITLE
Make OUTSDIF.d problem dependent

### PR DESCRIPTION
**Pull request by anriseth**
This allows different `CUTEstModels` to be run in parallel.

I don't know that `AUTOMAT.d` does, but I'm storing one for each model in case someone knows what to do with them.

Fixes https://github.com/JuliaSmoothOptimizers/CUTEst.jl/issues/51#issuecomment-354757852

### CODE REVIEW

**Comment by abelsiqueira** [comment]
I tried running the code on #51 using `julia -p 2`, but it didn't work for me. Am I doing something wrong?

**Comment by anriseth** [comment]
You need to decode each of the problems in serial first:
```jl
addprocs(2)
@everywhere using CUTEst
@everywhere function opt(name, decode)
    nlp = CUTEstModel(name;decode=decode)
    retval = obj(nlp,nlp.meta.x0)
    #retval = nlp.meta.nvar
    finalize(nlp)
    retval
end

probs = sort(CUTEst.select(contype="unc",max_var=5))
map(x->opt(x,true), probs)
pmap(x->opt(x,false), probs)
```

**Comment by abelsiqueira** [comment]
Yes, it worked now, thanks.

**Comment by anriseth** [comment]
I've included an example for the README. Let me know if you want it elsewhere.

**Comment by abelsiqueira** [comment]
Thank you

**Pull request merged**
