### PR TITLE
Fix hess_coord when obj_weight is zero

### PR DESCRIPTION
**Pull request by abelsiqueira**
Found with `dercheck.jl`.

### CODE REVIEW

**Comment by dpo** [comment]
We should actively use `dercheck` in the tests.

**Comment by abelsiqueira** [comment]
I'm putting it on `dercheck`, it shouldn't be a problem anymore.
I'm still having problems with `AmplNLReader` though.

**Comment by dpo** [comment]
Do you mean that you get erroneous derivatives?

**Comment by abelsiqueira** [comment]
Yes. In this case, the Hessian. I'm not sure how Ampl works, but I'm calling `hess(nlp_ampl, nlp_ampl.meta.x0)` right after `consistency_functions` and the value is not what's expected.

**Comment by dpo** [comment]
My guess is that it's the usual AMPL trap where you have to evaluate the function at x before you can evaluate its Hessian at x. Try calling `obj()` at the desired point before calling `hess()`.

**Comment by abelsiqueira** [comment]
Yes, that was it. Didn't know about that. It's fixed now. This can me merged.

**Comment by dpo** [comment]
Thanks!

**Pull request merged**
