### PR TITLE
Add an option to use our own version of CUTEst

### PR DESCRIPTION
**Pull request by amontoison**
@AndrewLister-STFC

### CODE REVIEW

**Comment by dpo** [comment]
I’m not a big fan of this. The Julia interface could be out of sync with the version of CUTEst that the user has installed. Instead, I would very much prefer that we cook up a way to use the CUTEst JLL from outside Julia.

**Comment by amontoison** [comment]
This backdoor is not documented.
It's a way to test new modifications or a new version of a package before that we precompile them with Yggdrasil.
It's what we do for HSL.jl, GALAHAD.jl, MUMPS.jl, QRMumps.jl, etc...

**Comment by amontoison** [comment]
I also try to recompile CUTEst with Yggdrasil (https://github.com/JuliaPackaging/Yggdrasil/pull/7924) for Andrew.
He sent me an email for that.
He would like to use the single precision version of CUTEst that Nick recently updated with the Julia interface CUTEst.jl.

**Comment by dpo** [comment]
Then we should at least display `@warn` messages alerting the user that this usage is not supported and that they’re using an external CUTEst library at their own risk.

**Pull request closed without merging**
