### PR TITLE
Attempt to detect a working CUTEst setup

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
This works for me locally with an existing installation of CUTEst. Could you also test at your end?

**Comment by abelsiqueira** [comment]
Yes, it is! Thank you.

**Comment by dpo** [comment]
Not sure why it's decided to build gcc from source on osx...

**Comment by abelsiqueira** [comment]
On homebrew-cutest it doesn't?

**Comment by dpo** [comment]
Ah it's because osx 10.9 is no longer supported by Homebrew. I need to request a more recent one.

**Comment by dpo** [comment]
Actually, the problem is something else. When installing CUTEst on 10.11, the gcc bottle is poured: https://travis-ci.org/optimizers/homebrew-cutest/jobs/165556609#L150

But when using Julia Homebrew, it isn't... Not sure what the problem is...

**Comment by dpo** [comment]
I temporarily added a `travis_wait` to see if the build completes.

**Comment by dpo** [comment]
Are osx failures a Travis bug??? I can't see another explanation at the moment.

**Comment by dpo** [comment]
Ok, I think I understand. It's just that the gcc bottles in Homebrew aren't relocatable, so Homebrew.jl compiles from source.

**Comment by abelsiqueira** [comment]
Sorry I haven't been helful. I really don't know much about osx and homebrew.
Can I merge this?

**Comment by dpo** [comment]
No problem. I cleaned up the PR. If the build passes, it should be good to go.

**Comment by abelsiqueira** [comment]
Thank you.

**Pull request merged**
