### PR TITLE
Use CUTEst_jll 2.0.6

### PR DESCRIPTION
**Pull request by amontoison**

### CODE REVIEW

**Comment by lrsantos11** [comment]
Guys, without 2.0.5 we cannot use `CUTEst.jl` on arm Macs. Any update on this?

**Comment by amontoison** [comment]
@dpo I propose to recompile the version "2.0.4" of `CUTEST_jll`. The last modifications in CUTEST break things here.
We just need to use the version number "2.0.6" for the Artifact.

**Comment by amontoison** [comment]
> Guys, without `CUTEst_jll 2.0.5` one cannot use `CUTEst.jl` on arm Macs. Any update on this?

@lrsantos11
I just recompiled CUTEst with Yggdrasil (https://github.com/JuliaPackaging/Yggdrasil/pull/6461).
I will update this PR asap.

**Comment by dpo** [comment]
Excellent! Thank you!

**Pull request merged**
