### PR TITLE
Fix for 0.6

### PR DESCRIPTION
**Pull request by abelsiqueira**
Needs [NLPModels update](https://github.com/JuliaSmoothOptimizers/NLPModels.jl/issues/84).

### CODE REVIEW

**Comment by dpo** [comment]
Thanks. This looks good. In the future, it would be clearer if you could document your changes and break them up into separate commits (and perhaps separate PRs). For example, in this case:

1. fix array initialization
2. phase out FactCheck.

**Comment by abelsiqueira** [comment]
Sorry about that, will improve in the future.

**Comment by abelsiqueira** [comment]
There was an error installing CUTEst on OSX [here](https://travis-ci.org/JuliaSmoothOptimizers/CUTEst.jl/jobs/211591114#L1368).

**Comment by dpo** [comment]
I just made new releases of everything. You probably need to update your Linux build script. An important change is that the release for MASTSIF has moved to Gitlab due to Github's more stringent file size limits. The current release can be downloaded from https://gitlab.com/dpo/mastsif-mirror/tags.

**Comment by abelsiqueira** [comment]
I had to rebase this, so I went ahead and split it into smaller commits. I added an additional commit to disallow failures on 0.6.

**Comment by pkofod** [comment]
would love if CUTEst could work on v0.6 soon :)

**Comment by dpo** [comment]
@abelsiqueira Good to go?

**Comment by abelsiqueira** [comment]
Yes

**Pull request merged**
