### PR TITLE
draft single precision support

### PR DESCRIPTION
**Pull request by dpo**
These are preliminary changes to support calling CUTEst in single precision. I haven't yet added single-precision tests. I see test failures locally that are probably due to an updated SIF collection (see #176).

The changes look a bit messy because I took the docstrings out of the `@eval` blocks.

### CODE REVIEW

**Comment by dpo** [comment]
@abelsiqueira Does your CUTEst installer also install the single precision library? If not, we're going to need it.

**Comment by abelsiqueira** [comment]
Updating here: https://github.com/abelsiqueira/linux-cutest/pull/15

**Comment by dpo** [comment]
`https://raw.githubusercontent.com/abelsiqueira/linux-cutest/v0.4.2/install.sh` still says `VERSION=0.4.1`. Not sure if it matters. I'll update the version number in `build.jl` and see if it works.

**Comment by dpo** [comment]
It's looking good! The Linux tests pass. Now I'll have to add single-precision tests.

**Comment by abelsiqueira** [comment]
Looking very good, thanks.

**Comment by abelsiqueira** [comment]
[This](https://github.com/JuliaSmoothOptimizers/NLPModels.jl/blob/master/test/multiple-precision.jl) is what's being tested in `NLPModels.jl`, perhaps it can be reused.

**Comment by dpo** [comment]
Yes, those are definitely important tests.

**Comment by amontoison** [comment]
Done in #366

**Pull request closed without merging**
