### PR TITLE
Remove NLPModels docstrings and add link to API in the docs

### PR DESCRIPTION
**Pull request by abelsiqueira**
The docstrings were duplicated.

### CODE REVIEW

**Comment by dpo** [comment]
Yes, that was a bit weird. Thank you. Confusingly, Documenter complained about *missing* docstrings!

**Comment by abelsiqueira** [comment]
It was because `hess_structure!` didn't have a docstring, but it was included in `api.md`. The solution would be adding `@doc (@doc NLPModels.hess_structure!)` in the function definition. I then realized that removing the docstrings altogether would be better.

**Comment by dpo** [comment]
It [did](https://github.com/JuliaSmoothOptimizers/CUTEst.jl/commit/c7135e403699c769afaf4fe9bf71adeaee772378#diff-582c252a3e3e6631014cd1bc8d0ccf3eR349) (line 349). Other methods were similar, but Documenter wasn't complaining about them.

**Comment by abelsiqueira** [comment]
I see, I was looking at [this line](https://github.com/JuliaSmoothOptimizers/CUTEst.jl/commit/c7135e403699c769afaf4fe9bf71adeaee772378#diff-582c252a3e3e6631014cd1bc8d0ccf3eR327) (327).

It might be that the problem was that it didn't have `NLPModels.` preceding the function name. This also begs the question if the function is exported.

**Comment by dpo** [comment]
I wish Documenter (and Julia in general) had good error messages...

**Pull request merged**
