### PR TITLE
package SIF collection as artifact

### PR DESCRIPTION
**Pull request by dpo**
Use Julia 1.3's artifact feature to download and install the SIF collection once and for all. According to the docs, the artifact will be shared by several installations of CUTEst.jl (say, in several environments), and so will be downloaded only once.

### CODE REVIEW

**Comment by dpo** [comment]
I like the result but this was incredibly frustrating to get working.

**Comment by dpo** [comment]
I agree that it would be good to fetch the collection first thing, but what if the user already has the collection and has set MASTSIF?

**Comment by abelsiqueira** [comment]
Inside `__init__`, if the user doesn't have `MASTSIF` set, we define a default one. Instead, we could fetch.

Also, just noticed an error, `ENV["MASTSIF"]` is lost after closing `julia`, even after `fetch_sif_problems()`. So the default `MASTSIF` should at least point to the same artifact place.

**Comment by dpo** [comment]
I set it to `CUTEst-2.0.3/sif` by default in case the user doesn't want to download the whole thing. Should we just go ahead and download?

Not sure I understand the error. Every time I restart Julia, MASTSIF points to `CUTEst-2.0.3/sif`, and if I call `fetch_sif_problems()`, it points to the whole collection (without downloading again).

**Comment by abelsiqueira** [comment]
But then I have to call `fetch_sif_problems()` every time, which is counter-intuitive. I think we should download by default if there is no `MASTSIF`. The problems in `CUTEst-2.0.3/sif` are only useful for testing.

**Comment by dpo** [comment]
I agree, but if the user has already set `MASTSIF`, then how do we change `MASTSIF` (after `__init__`) to point to the full collection?

**Comment by abelsiqueira** [comment]
Ask the user to unset `MASTSIF`. If the user has a working `MASTSIF`, we won't need to use the artifact. If he has no `MASTSIF`, he will use the artifact. If he has a `MASTSIF` that doesn't work, he should unset it.
I'm looking into what is more common, and I think that most people will use CUTEst.jl without any CUTEst installation because they're using only Julia. In second most used, I think they'll be comparing a non-julia solver with a Julia solver, in which case he'll have both, so either MASTSIF will work.

Just noticed: do we have an `export_cutest_env()` so the user can install CUTEst.jl and use it outside of Julia?

**Comment by dpo** [comment]
I now point to the main MASTSIF unless the env var is already set. The method `set_mastsif()` points it to the main collection. The user can explicitly change the env var in Julia if they want to point to some other location, but we needed a mechanism to reset to the artifact.

> do we have an export_cutest_env() so the user can install CUTEst.jl and use it outside of Julia?

Let's open an issue.

**Comment by abelsiqueira** [comment]
Thanks

**Pull request merged**
